// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { main, config } from "../models";

export function ApplyUpdate(): Promise<void>;

export function CheckUpdate(): Promise<main.UpdateInfo>;

export function DownloadUpdate(arg1: string, arg2: string): Promise<void>;

export function EngineStatus(): Promise<main.EngineStatus>;

export function GetAppInfo(): Promise<main.AppInfo>;

export function ListInputDevices(): Promise<main.InputDevice[]>;

export function OpenInFolder(arg1: string): Promise<void>;

export function ProbeMedia(arg1: string): Promise<main.MediaInfo>;

export function ProbeMediaExtended(arg1: string): Promise<main.ExtendedMediaInfo>;

export function RollbackUpdate(): Promise<void>;

export function RunFFmpeg(arg1: main.RunRequest): Promise<void>;

export function SelectDirectory(): Promise<string>;

export function SelectMediaFile(): Promise<string>;

export function SelectMediaFiles(): Promise<string[]>;

export function SelectOutputPath(arg1: string): Promise<string>;

export function SelectSubtitleFile(): Promise<string>;

export function CheckProxy(arg1: string): Promise<void>;

export function GetSettings(): Promise<config.AppSettings>;

export function SaveSettings(arg1: config.AppSettings): Promise<void>;
