// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { main } from "../models";

export function EngineStatus(): Promise<main.EngineStatus>;

export function ListInputDevices(): Promise<main.InputDevice[]>;

export function OpenInFolder(arg1: string): Promise<void>;

export function ProbeMedia(arg1: string): Promise<main.MediaInfo>;

export function ProbeMediaExtended(arg1: string): Promise<main.ExtendedMediaInfo>;

export function RunFFmpeg(arg1: main.RunRequest): Promise<void>;

export function SelectDirectory(): Promise<string>;

export function SelectMediaFile(): Promise<string>;

export function SelectMediaFiles(): Promise<string[]>;

export function SelectOutputPath(arg1: string): Promise<string>;

export function SelectSubtitleFile(): Promise<string>;
