// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CheckProxy(arg1) {
  return window['go']['main']['App']['CheckProxy'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function DownloadUpdate(arg1, arg2) {
  return window['go']['main']['App']['DownloadUpdate'](arg1, arg2);
}

export function EngineStatus() {
  return window['go']['main']['App']['EngineStatus']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListInputDevices() {
  return window['go']['main']['App']['ListInputDevices']();
}

export function OpenInFolder(arg1) {
  return window['go']['main']['App']['OpenInFolder'](arg1);
}

export function ProbeMedia(arg1) {
  return window['go']['main']['App']['ProbeMedia'](arg1);
}

export function ProbeMediaExtended(arg1) {
  return window['go']['main']['App']['ProbeMediaExtended'](arg1);
}

export function RollbackUpdate() {
  return window['go']['main']['App']['RollbackUpdate']();
}

export function RunFFmpeg(arg1) {
  return window['go']['main']['App']['RunFFmpeg'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectMediaFile() {
  return window['go']['main']['App']['SelectMediaFile']();
}

export function SelectMediaFiles() {
  return window['go']['main']['App']['SelectMediaFiles']();
}

export function SelectOutputPath(arg1) {
  return window['go']['main']['App']['SelectOutputPath'](arg1);
}

export function SelectSubtitleFile() {
  return window['go']['main']['App']['SelectSubtitleFile']();
}

export function StopFFmpeg() {
  return window['go']['main']['App']['StopFFmpeg']();
}

export function WriteConcatList(arg1) {
  return window['go']['main']['App']['WriteConcatList'](arg1);
}
