// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EngineStatus() {
  return window['go']['main']['App']['EngineStatus']();
}

export function OpenInFolder(arg1) {
  return window['go']['main']['App']['OpenInFolder'](arg1);
}

export function ProbeMedia(arg1) {
  return window['go']['main']['App']['ProbeMedia'](arg1);
}

export function RunFFmpeg(arg1) {
  return window['go']['main']['App']['RunFFmpeg'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectMediaFile() {
  return window['go']['main']['App']['SelectMediaFile']();
}

export function SelectOutputPath(arg1) {
  return window['go']['main']['App']['SelectOutputPath'](arg1);
}
